name: intake_CMIP6_v0
channels:
  - conda-forge
dependencies:
  # Pangeo (version needs to fit with Dockerfile)
  # https://medium.com/pangeo/managing-environments-5604d848367a
  - pangeo-notebook==2020.10.08
  # NetCDF files
  - xarray
  - netcdf4
  - nc-time-axis
  # Regrid
  - esmpy
  - xesmf
  # CMIP6
  - intake-esm
  - gcsfs
  - zarr
  # Plots
  - proplot=0.6.4
  - matplotlib=3.2.0
  - cartopy
  # Miscellaneous
  - python-graphviz
  - nbresuse
